### ISSUE TITLE
How to use generated layouts on Flipper?

### ISSUE THREAD

**Issue by TheT3ngu** [dummy-decoy/flipperzero_badusb_kl#13]
Dumb question, but... How do we use a generated layout on the Flipper in badUSB? Does there need to be some kind of command in each ducky script that tells the Flipper what layout to use for the attack, or how do we tell the Flipper which layout to use?

**Comment by FerdinandoPH** [comment]
I've got the same question

**Comment by g1lby** [comment]
same question

**Comment by FerdinandoPH** [comment]
I found out that there is an unofficial software (flipper unlocked) that lets you use different keyboard layouts.

**Comment by dummy-decoy** [comment]
the feature exists in the official firmware. see step 3 of the paragraph "Using your Flipper Zero as a BadUSB device" here:
https://docs.flipper.net/bad-usb#uk2m2
